name: Trigger auto deployment for mycontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/mycontainerapp-AutoDeployTrigger-6b13682c-68bb-4278-a93a-6f20840614de.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: mycontainerapp20230630132604.azurecr.io
          registryUsername: ${{ secrets.MYCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: mycontainerapp
          resourceGroup: Sandbox_Kai
          imageToBuild: mycontainerapp20230630132604.azurecr.io/mycontainerapp:${{ github.sha }}
          dockerfilePath: Dockerfile

     

